export const enLang = {
    signIn: "Sign In",
    login: "Login",
    registration: "Registration",
    password: "Password",
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
    register: "Register",
    securityToken: "Security Token",
    role: "Role",
    creationDate: "Creation Date",
    edit: "Edit",
    remove: "Remove",
    acceptRemoveTitle: "Are you sure you want to delete this entry?",
    acceptRemoveMessage: "You will not be able to recover deleted data.",
    cancel: "Cancel",
    editing: "Editing",
    addNew: "Add New Record",
    something: "Something",
    action: "Action",
    address: "Address",
    locationName: "Location Name",
    messageAddNewSuccess: "The record has been added",
    messageAddNewFailure: "Something got wrong. The record has not been added",
    messageUpdateSuccess: "The record has been updated",
    messageUpdateFailure: "Something got wrong. The record has not been updated",
    messageRemoveSuccess: "The record has been deleted",
    messageRemoveFailure: "Something got wrong. The record has not been deleted",
    userId: "User Id",
    locationId: "Location Id",
    themeId: "Theme Id",
    title: "Title",
    description: "Description"
}