export const enLang = {
    signIn: "Sign In",
    login: "Login",
    registration: "Registration",
    password: "Password",
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
    register: "Register",
    securityToken: "Security Token",
    role: "Role",
    creationDate: "Creation Date",
    edit: "Edit",
    remove: "Remove",
    acceptRemoveTitle: "Are you sure you want to delete this entry?",
    acceptRemoveMessage: "You will not be able to recover deleted data.",
    cancel: "Cancel",
    editing: "Editing",
    addNew: "Add New Record",
    something: "Something",
    action: "Action",
    address: "Address",
    locationName: "Location Name",
    messageAddNewSuccess: "The record has been added",
    messageAddNewFailure: "Something got wrong. The record has not been added",
    messageUpdateSuccess: "The record has been updated",
    messageUpdateFailure: "Something got wrong. The record has not been updated",
    messageRemoveSuccess: "The record has been deleted",
    messageRemoveFailure: "Something got wrong. The record has not been deleted",
    userId: "User Id",
    locationId: "Location Id",
    themeId: "Theme Id",
    title: "Title",
    description: "Description",
    orderId: "Order Id",
    message: "Message",
    orderStatus: "Order Status",
    senderId: "Sender Id",
    lockerId: "Locker Id",
    lockerToken: "Locker Token",
    isClosed: "Is closed",
    isEnabled: "Is enabled",
    timeOfLastUse: "Time of last use",
    logId: "Usage Log Id",
    startTime: "Start Time",
    endTime: "End Time",
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    scheduleId: "Schedule Id",
    dayOfWeek: "Day of week",
    dashboard: "Dashboard",
    data: "Data",
    language: "Language",
    signOut: "Sign out",
    import: "Import",
    export: "Export",
    users: "Users",
    locations: "Locations",
    locationOwners: "Location Owners",
    lockers: "Lockers",
    lockerUsageLogs: "Locker Usage Logs",
    themes: "Themes",
    orders: "Orders",
    schedules: "Schedules"
}

export const uaLang = {
    signIn: "Увійти",
    login: "Логін",
    registration: "Реєстрація",
    password: "Пароль",
    fullName: "Повне ім'я",
    email: "Email",
    phoneNumber: "Номер телефону",
    register: "Зареєструватись",
    securityToken: "Токен безпеки",
    role: "Роль",
    creationDate: "Дата створення",
    edit: "Редагувати",
    remove: "Видалити",
    acceptRemoveTitle: "Ви впевнені, що хочете видалити цей запис?",
    acceptRemoveMessage: "Ви не зможете відновити видалені дані.",
    cancel: "Скасувати",
    editing: "Редагування",
    addNew: "Додати новий запис",
    something: "Щось",
    action: "Дія",
    address: "Адреса",
    locationName: "Назва локації",
    messageAddNewSuccess: "Запис додано",
    messageAddNewFailure: "Щось сталося не так. Запис не додано",
    messageUpdateSuccess: "Запис оновлено",
    messageUpdateFailure: "Щось сталося не так. Запис не оновлено",
    messageRemoveSuccess: "Запис видалено",
    messageRemoveFailure: "Щось сталося не так. Запис не видалено",
    userId: "Id користувача",
    locationId: "Id локації",
    themeId: "Id теми",
    title: "Заголовок",
    description: "Опис",
    orderId: "Id замовлення",
    message: "Повідомлення",
    orderStatus: "Статус замовлення",
    senderId: "Id відправника",
    lockerId: "Id осередку",
    lockerToken: "Токен осередку",
    isClosed: "Зачинено",
    isEnabled: "Вімкнено",
    timeOfLastUse: "Час останнього використання",
    logId: "Id історії використання",
    startTime: "Час початку",
    endTime: "Час закінчення",
    sunday: "Неділя",
    monday: "Понеділок",
    tuesday: "Вівторок",
    wednesday: "Середа",
    thursday: "Четвер",
    friday: "П'ятниця",
    saturday: "Субота",
    scheduleId: "Id графіку",
    dayOfWeek: "День тижня",
    dashboard: "Панель приладів",
    data: "Дані",
    language: "Мова",
    signOut: "Вийти",
    import: "Імпорт",
    export: "Експорт",
    users: "Користувачі",
    locations: "Локації",
    locationOwners: "Власники локацій",
    lockers: "Осередки зберігання",
    lockerUsageLogs: "Журнал використання осередків",
    themes: "Теми замовлень",
    orders: "Замовлення",
    schedules: "Графіки"
}