export const enLang = {
    signIn: "Sign In",
    login: "Login",
    registration: "Registration",
    password: "Password",
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
    register: "Register",
    securityToken: "Security Token",
    role: "Role",
    creationDate: "Creation Date",
    edit: "Edit",
    remove: "Remove",
    acceptRemoveTitle: "Are you sure you want to delete this entry?",
    acceptRemoveMessage: "You will not be able to recover deleted data.",
    cancel: "Cancel",
    editing: "Editing",
    addNew: "Add New Record",
    something: "Something",
    action: "Action"
}